Refactor to allow content_length limitation to webpreview generation
algoo/webpreview pull request #1
Opened 2022-02-22 13:41 UTC by inkhey

Refactoring proposal to : 
- add content_length limit that work for all requests (with and without content_length)
- have better separation between the request code and the html parsing code making easier for other program to reuse the same request to do other stuff.

This proposals:
- Don't break automated tests.
- Should not change much behavior

If validated, i will propose this change upstream.

2022-02-23 08:41 UTC, Haskaris requested changes

2022-02-23 08:41 UTC, Haskaris commented on webpreview/previews.py
> +            #
```suggestion
```

2022-02-23 08:41 UTC, Haskaris commented on webpreview/previews.py
> +def web_preview(url, timeout=None, headers=None, absolute_image_url=False, content=None, parser=None, content_length_limit = None):
```suggestion
def web_preview(url, timeout=None, headers=None, absolute_image_url=False, content=None, parser=None, content_length_limit=None):
```

2022-02-28 09:59 UTC, merged

2022-02-28 14:06 UTC, grignards commented on webpreview/previews.py
> +class LengthLimitedResponse(requests.Response):
I do not understand why this class inherits from `requests.Response` and is still given a response instance.
If it is a wrapper it shouldn't inherit I think.
Also I'm unsure a class is needed here, wouldn't be simpler to put `binary_content` + `text_content` in a simple function which is given a `request.Response` instance?

2022-02-28 14:06 UTC, grignards commented on webpreview/previews.py
> +class LengthLimitedResponse(requests.Response):
And max_content_length would be a more explicit naming I think.

2022-02-28 14:06 UTC, grignards commented on webpreview/previews.py
> +                raise Exception()
raise `Exception`? Seems strange to me.

2022-02-28 14:06 UTC, grignards commented on webpreview/previews.py
> +            url = "http://" + url
I'm unsure why is this change necessary (in regards to the original code), but removing the `try` clause would be easier to understand (raise an exception to catch it in the same block).

2022-02-28 14:14 UTC, inkhey commented on webpreview/previews.py
> +            url = "http://" + url
Right, the original code does a request, this code avoid the need of request but you're right we can make things simpler. i just don't see it.

2022-02-28 15:06 UTC, inkhey commented on webpreview/previews.py
> +class LengthLimitedResponse(requests.Response):
renamed to MaxLengthResponse

2022-02-28 15:06 UTC, inkhey commented on webpreview/previews.py
> +                raise Exception()
fixed with specific exception.

2022-02-28 15:06 UTC, inkhey commented on webpreview/previews.py
> +            url = "http://" + url
simplified.